'use client';

import React from 'react';
import { motion } from 'framer-motion';
import { Code, Eye, Bug, Terminal, GitCommit, Sparkles } from 'lucide-react';

const FEATURES = [
  {
    icon: Code,
    title: 'Active Coding Metrics',
    description: 'Tracks keystrokes, editor saves, and document changes to monitor active editing increments.',
    benefit: 'See how much time is spent reviewing, documenting, and writing code.',
    color: 'text-accent-primary',
    bgColor: 'bg-accent-primary/10 border-accent-primary/20',
    gridClass: 'md:col-span-8',
    visualType: 'editor'
  },
  {
    icon: Eye,
    title: 'Studying & Code Reading',
    description: 'Monitors scroll events, cursor lines, and browser research tags to log passive reading states.',
    benefit: 'Understand how much time is spent research-studying versus typing.',
    color: 'text-accent-blue',
    bgColor: 'bg-accent-blue/10 border-accent-blue/20',
    gridClass: 'md:col-span-4',
    visualType: 'simple'
  },
  {
    icon: Bug,
    title: 'Debugging Sessions',
    description: 'Links directly into VS Code debugger state machines to register active investigation hours.',
    benefit: 'Measure hours spent diagnosing and rectifying compiler logic errors.',
    color: 'text-accent-red',
    bgColor: 'bg-accent-red/10 border-accent-red/20',
    gridClass: 'md:col-span-4',
    visualType: 'simple'
  },
  {
    icon: Terminal,
    title: 'Terminal Auditing',
    description: 'Intercepts CLI executions to catalog setups like npm installs, builds, and test runs.',
    benefit: 'Identify how shell tasks and dev scripts eat into your core focus cycles.',
    color: 'text-accent-green',
    bgColor: 'bg-accent-green/10 border-accent-green/20',
    gridClass: 'md:col-span-8',
    visualType: 'terminal'
  },
  {
    icon: Sparkles,
    title: 'AI Companion Multiplier',
    description: 'Counts completions generated by Copilot, Continue, or custom LLM chats to calculate augmented work ratios.',
    benefit: 'Measure your AI multiplier to find where generative tools actually help.',
    color: 'text-accent-purple',
    bgColor: 'bg-accent-purple/10 border-accent-purple/20',
    gridClass: 'md:col-span-6',
    visualType: 'simple'
  },
  {
    icon: GitCommit,
    title: 'Git Versioning Fuses',
    description: 'Tracks commit counts, branch switches, merges, and rebases to stitch VCS timelines together.',
    benefit: 'Correlate pull request logs and version control shifts with daily focus blocks.',
    color: 'text-accent-orange',
    bgColor: 'bg-accent-orange/10 border-accent-orange/20',
    gridClass: 'md:col-span-6',
    visualType: 'simple'
  }
];

export default function FeatureGrid() {
  const handleMouseMove = (e: React.MouseEvent<HTMLDivElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;
    e.currentTarget.style.setProperty('--mouse-x', `${x}px`);
    e.currentTarget.style.setProperty('--mouse-y', `${y}px`);
  };

  return (
    <section id="features" className="py-28 px-4 max-w-7xl mx-auto relative border-t border-border-default">
      {/* Background spotlights */}
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] radial-glow-accent pointer-events-none -z-10" />

      <div className="text-center max-w-3xl mx-auto mb-20">
        <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-text-primary font-sans">
          Advanced IDE Heuristics
        </h2>
        <p className="mt-4 text-text-secondary text-sm md:text-base leading-relaxed">
          Forget start, stop, and pause triggers. Our background sync listeners monitor system levels automatically so you can focus on building.
        </p>
      </div>

      {/* Bento Grid Layout */}
      <div className="grid grid-cols-1 md:grid-cols-12 gap-6">
        {FEATURES.map((feature, idx) => {
          const Icon = feature.icon;
          return (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true, margin: '-100px' }}
              transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1], delay: idx * 0.05 }}
              onMouseMove={handleMouseMove}
              className={`p-8 rounded-2xl border border-card-border bg-card-bg hover:bg-card-hover-bg hover:border-card-hover-border transition-all duration-500 flex flex-col justify-between group relative overflow-hidden shadow-sm dark:shadow-none col-span-12 ${feature.gridClass}`}
            >
              <div className="flex flex-col lg:flex-row justify-between gap-6 w-full">
                <div className="flex-1">
                  {/* Glowing Icon Container */}
                  <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-6 border transition-transform duration-500 group-hover:scale-105 ${feature.bgColor}`}>
                    <Icon size={20} className={feature.color} />
                  </div>
                  <h3 className="text-xl font-bold text-text-primary">{feature.title}</h3>
                  <p className="mt-3 text-text-body text-sm leading-relaxed">{feature.description}</p>
                </div>

                {/* Embedded visuals inside Bento cards */}
                {feature.visualType === 'editor' && (
                  <div className="hidden lg:block w-72 h-36 rounded-lg bg-card-hover-bg/80 border border-border-default p-3 font-mono text-[9px] text-text-secondary overflow-hidden shrink-0 select-none">
                    <div className="flex items-center justify-between pb-2 border-b border-border-default mb-2">
                      <span className="text-text-muted">src/components/landing/Header.tsx</span>
                      <span className="text-accent-primary text-[8px] animate-pulse">● TRACKING</span>
                    </div>
                    <div className="space-y-1">
                      <div><span className="text-accent-purple">import</span> React <span className="text-accent-purple">from</span> <span className="text-accent-green">'react'</span>;</div>
                      <div><span className="text-accent-purple">export default function</span> <span className="text-accent-blue">Header</span>() &#123;</div>
                      <div className="pl-3"><span className="text-accent-purple">return</span> (</div>
                      <div className="pl-6 text-text-primary bg-accent-primary/10 border-l border-accent-primary/40">&lt;<span className="text-accent-blue">header</span> className=<span className="text-accent-green">"fixed z-50..."</span>&gt;</div>
                      <div className="pl-9 text-text-primary bg-accent-primary/10 border-l border-accent-primary/40">&lt;<span className="text-accent-blue">div</span> className=<span className="text-accent-green">"flex justify..."</span>&gt;</div>
                      <div className="pl-6">&lt;/<span className="text-accent-blue">header</span>&gt;</div>
                    </div>
                  </div>
                )}

                {feature.visualType === 'terminal' && (
                  <div className="hidden lg:block w-72 h-36 rounded-lg bg-card-hover-bg/80 border border-border-default p-3 font-mono text-[9px] text-text-secondary overflow-hidden shrink-0 select-none">
                    <div className="flex justify-between items-center pb-2 border-b border-border-default mb-2">
                      <span className="text-text-muted">zsh</span>
                      <span className="text-accent-green text-[8px]">● CAPTURED</span>
                    </div>
                    <div className="space-y-1">
                      <div className="text-text-primary">$ npm install tailwindcss</div>
                      <div className="text-text-muted">  added 142 packages, and audited 143 packages in 4s</div>
                      <div className="text-text-primary">$ npm run dev</div>
                      <div className="text-accent-primary">  [vite] local server running at http://localhost:5173/</div>
                    </div>
                  </div>
                )}
              </div>

              {/* Benefit footer */}
              <div className="mt-8 pt-4 border-t border-border-default flex items-center justify-between text-xs">
                <div>
                  <span className="text-[10px] font-bold text-accent-primary uppercase tracking-wider block">Outcome Benefit</span>
                  <span className="text-text-secondary font-medium mt-0.5 block">{feature.benefit}</span>
                </div>
              </div>
            </motion.div>
          );
        })}
      </div>
    </section>
  );
}
